# TUPLES IN PYTHON.
# ---> IT is a built in data type that lets us create immutable sequences of values.
# ---> with single value we have to put , coma if we dont put
#     any coma python will take it as a integer,float or string value.
 

# tup=(4,5,6)
# print(type(tup))


tup=(2,1,3,1)
print(tup[0])
print(tup[2])

#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

# ---> TUPLIS METHOD

# 1} tup.index(el)  returs index of first occurance.

# tup=(7,8,9,6)
# print(tup.index(8))

#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

# 2} tup.count(el)  counts the total occurance of element.
 # ---> it main function is to tell us how many time a certai element occured.
 
# tup=(1,2,2,2,3,3,4,5,4,6,4,7,4,8)
# print(tup.count(4))

#\\\\\\\\\\\\\\\ END HERE \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\