# 1]WRITE A PROGRAM TO INPUT 2 VALUES AND PRINT THERE SUM.

# val1=int(input("enter nember 1:"))
# val2=int(input("enter number3:"))

# print("addition=" , val1+val2)

#########################################################3

#2]WAP to input side of a squqre and print it area
 
# side=int(input("enter the value:"))

# print('area=', side*side)

##########################################

#3] WAP TO INPUT 2 FLOATING POINT NUMBER AND PRINT THEIR AVERAGE.

# a=float(input("enter first no:"))
# b=float(input("enter second no:"))
# print("ANSWER" ,a+b/2)

#######################################################

#4} WAP to input 2 int numbers,A and B.
#print true if a is greater than equal to b.if not print FALSE.

a=int(input("enter first number:"))
b=int(input("enter second number:"))
print("the answer:" , a>=b,)
